// This file was auto-generated by Fern from our API Definition.

import * as Speechify from "../../../src/api/index";
import { SpeechifyClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ConsentChallengesClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "Jane Doe" };
        const rawResponseBody = {
            id: "9f8a1c04e7b24d1e8a3f",
            phrase: "I agree to have my voice cloned by Speechify. My verification code is four seven two nine.",
            expires_at: "2026-10-01T09:05:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .header("Idempotency-Key", "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.voices.consentChallenges.create({
            "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            full_name: "Jane Doe",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.ForbiddenError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.BadGatewayError);
    });

    test("create (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { full_name: "full_name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/voices/consent-challenges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.consentChallenges.create({
                full_name: "full_name",
            });
        }).rejects.toThrow(Speechify.ServiceUnavailableError);
    });
});
