// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
 *         consumer_key_id: "ckey_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface RevokeKeyKeysRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
    /** Consumer key id (prefixed external id, `ckey_...`). */
    consumer_key_id: string;
}
