// This file was auto-generated by Fern from our API Definition.

export const ListVoicesRequestGender = {
    Male: "male",
    Female: "female",
    NotSpecified: "not_specified",
} as const;
export type ListVoicesRequestGender = (typeof ListVoicesRequestGender)[keyof typeof ListVoicesRequestGender];
