// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://example.com/speechify/webhooks",
 *         enabled_events: ["project.spend_budget.warning"],
 *         description: "Example description."
 *     }
 */
export interface CreateWebhookEndpointRequest {
    /**
     * HTTPS destination for event deliveries. Must be a publicly
     * reachable host: loopback, private, link-local, and cloud-metadata
     * addresses (and reserved hostnames like `localhost`) are rejected.
     */
    url: string;
    /**
     * Optionally scope the endpoint to one project (prefixed
     * `proj_...` id): a scoped endpoint receives only that project's
     * events. Omit (or null) for workspace-wide - it receives every
     * project's events. An unknown id returns 404 project_not_found.
     * A project-pinned API key creates into its own project and
     * cannot name the workspace-wide tier.
     */
    project_id?: string | null;
    /** Catalog event names to subscribe to, or `["*"]` for all events. */
    enabled_events: string[];
    /**
     * Optional payload-shaping keys (see `WebhookEndpoint.include`).
     * Omit for the lean default.
     */
    include?: string[];
    /**
     * Optionally pin the endpoint's payload shape to a dated version
     * (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to use the
     * workspace's current version. An unknown version is rejected.
     */
    api_version?: string;
    description?: string | null;
}
