// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface GetEndpointsRequest {
    /** Webhook endpoint id (prefixed `whe_…`). */
    webhook_endpoint_id: string;
}
