// This file was auto-generated by Fern from our API Definition.

/** When true, each `speech.chunk` carries the word marks that became final with it, indexing the session's whole text. */
export const AudioStreamInputSpeechMarks = {
    True: "true",
    False: "false",
} as const;
export type AudioStreamInputSpeechMarks =
    (typeof AudioStreamInputSpeechMarks)[keyof typeof AudioStreamInputSpeechMarks];
