// This file was auto-generated by Fern from our API Definition.

/**
 * Client message on GET /v1/audio/stream/ws: no more text is coming. The server speaks everything it was sent, sends speech.done with reason closed, and closes the socket. Keep reading until speech.done arrives: closing the socket first abandons the audio still to come, and the segment it cuts is billed in full.
 */
export interface InputClose {
    type: InputClose.Type;
}

export namespace InputClose {
    export const Type = {
        InputClose: "input.close",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
