// This file was auto-generated by Fern from our API Definition.

/**
 * Client message on GET /v1/audio/stream/ws: text appended to what the session will speak. Send it as your application produces it, a few tokens at a time is fine; the server speaks each sentence once the next one starts, so a reply that arrives in pieces is cut at its sentence boundaries, not at the message boundaries. The text is spoken as plain text: SSML is read aloud, not interpreted. At most 20000 characters can wait to be spoken at once; more is refused with payload_too_large, which ends the session.
 */
export interface InputText {
    type: InputText.Type;
    /** The next piece of text. Include the spaces and newlines between words and sentences exactly as your source produced them: they are what tells the server a sentence has ended. */
    text: string;
}

export namespace InputText {
    export const Type = {
        InputText: "input.text",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
