// This file was auto-generated by Fern from our API Definition.

/**
 * Client message on GET /v1/audio/stream/ws: speak everything sent so far now, without waiting for its sentence to end. The server answers with speech.flushed once that audio has been sent, at once when nothing was waiting. Use it at the end of an LLM turn.
 */
export interface InputFlush {
    type: InputFlush.Type;
}

export namespace InputFlush {
    export const Type = {
        InputFlush: "input.flush",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
