// This file was auto-generated by Fern from our API Definition.

/**
 * Server event on GET /v1/audio/stream/ws: the audio for everything sent before an input.flush has been sent. One arrives for every input.flush, in order.
 */
export interface SpeechFlushed {
    type: SpeechFlushed.Type;
}

export namespace SpeechFlushed {
    export const Type = {
        SpeechFlushed: "speech.flushed",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
