// This file was auto-generated by Fern from our API Definition.

export interface SpeechDone {
    type: SpeechDone.Type;
    /** Number of billable characters processed. */
    billable_characters_count: number;
    /** Duration of the synthesized audio in milliseconds. */
    audio_duration_ms: number;
    /** closed: the client sent input.close and everything was spoken. idle: 60 seconds passed with nothing to speak and no message. session_limit: the session reached its 5 minute limit, and everything sent before it was spoken. shutdown: the server is restarting; reconnect, and the next session lands on another server. Ignore a reason you do not recognize. */
    reason: SpeechDone.Reason;
}

export namespace SpeechDone {
    export const Type = {
        SpeechDone: "speech.done",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** closed: the client sent input.close and everything was spoken. idle: 60 seconds passed with nothing to speak and no message. session_limit: the session reached its 5 minute limit, and everything sent before it was spoken. shutdown: the server is restarting; reconnect, and the next session lands on another server. Ignore a reason you do not recognize. */
    export const Reason = {
        Closed: "closed",
        Idle: "idle",
        SessionLimit: "session_limit",
        Shutdown: "shutdown",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
