// This file was auto-generated by Fern from our API Definition.

export const StreamWithTimestampsAudioRequestAccept = {
    AudioMpeg: "audio/mpeg",
    AudioOgg: "audio/ogg",
    AudioAac: "audio/aac",
    AudioPcm: "audio/pcm",
} as const;
export type StreamWithTimestampsAudioRequestAccept =
    (typeof StreamWithTimestampsAudioRequestAccept)[keyof typeof StreamWithTimestampsAudioRequestAccept];
