// This file was auto-generated by Fern from our API Definition.

import * as Speechify from "../../../src/api/index";
import { SpeechifyClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EndpointsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            next_cursor: "next_cursor",
            has_more: true,
            endpoints: [
                {
                    id: "whe_01kwxwcbyb6wk952swa0432cf1",
                    url: "https://example.com/speechify/webhooks",
                    project_id: "proj_01arz3ndektsv4rrffq69g5fav",
                    enabled_events: ["project.spend_budget.warning"],
                    include: ["include"],
                    api_version: "2026-06-28",
                    description: "Example description.",
                    disabled: false,
                    secret: "whsec_demo••••0000",
                    created_at: "2026-06-24T18:03:11Z",
                    updated_at: "2026-06-24T18:03:11Z",
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.webhooks.endpoints.list({
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
        });

        expect(expected.endpoints).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.endpoints).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.list();
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.list();
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.list();
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.list();
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.list();
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            url: "https://example.com/speechify/webhooks",
            enabled_events: ["project.spend_budget.warning"],
            description: "Example description.",
        };
        const rawResponseBody = {
            id: "whe_01kwxwcbyb6wk952swa0432cf1",
            url: "https://example.com/speechify/webhooks",
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
            enabled_events: ["project.spend_budget.warning"],
            include: ["include"],
            api_version: "2026-06-28",
            description: "Example description.",
            disabled: false,
            secret: "whsec_demo••••0000",
            created_at: "2026-06-24T18:03:11Z",
            updated_at: "2026-06-24T18:03:11Z",
        };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.endpoints.create({
            url: "https://example.com/speechify/webhooks",
            enabled_events: ["project.spend_budget.warning"],
            description: "Example description.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url", enabled_events: ["enabled_events", "enabled_events"] };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.create({
                url: "url",
                enabled_events: ["enabled_events", "enabled_events"],
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "whe_01kwxwcbyb6wk952swa0432cf1",
            url: "https://example.com/speechify/webhooks",
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
            enabled_events: ["project.spend_budget.warning"],
            include: ["include"],
            api_version: "2026-06-28",
            description: "Example description.",
            disabled: false,
            secret: "whsec_demo••••0000",
            created_at: "2026-06-24T18:03:11Z",
            updated_at: "2026-06-24T18:03:11Z",
        };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/whe_01jqr8x9zg5k2m3n4p5q6r7s8t")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.endpoints.get({
            webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.get({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.get({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.get({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.get({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/whe_01jqr8x9zg5k2m3n4p5q6r7s8t")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhooks.endpoints.delete({
            webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.delete({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.delete({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.delete({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.delete({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .delete("/v1/webhooks/endpoints/webhook_endpoint_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.delete({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            url: "https://example.com/webhook",
            enabled_events: ["example"],
            description: "Example description.",
            disabled: false,
        };
        const rawResponseBody = {
            id: "whe_01kwxwcbyb6wk952swa0432cf1",
            url: "https://example.com/speechify/webhooks",
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
            enabled_events: ["project.spend_budget.warning"],
            include: ["include"],
            api_version: "2026-06-28",
            description: "Example description.",
            disabled: false,
            secret: "whsec_demo••••0000",
            created_at: "2026-06-24T18:03:11Z",
            updated_at: "2026-06-24T18:03:11Z",
        };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/whe_01jqr8x9zg5k2m3n4p5q6r7s8t")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.endpoints.update({
            webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            url: "https://example.com/webhook",
            enabled_events: ["example"],
            description: "Example description.",
            disabled: false,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/webhooks/endpoints/webhook_endpoint_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.update({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("rotateSecret (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "whe_01kwxwcbyb6wk952swa0432cf1",
            url: "https://example.com/speechify/webhooks",
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
            enabled_events: ["project.spend_budget.warning"],
            include: ["include"],
            api_version: "2026-06-28",
            description: "Example description.",
            disabled: false,
            secret: "whsec_demo••••0000",
            created_at: "2026-06-24T18:03:11Z",
            updated_at: "2026-06-24T18:03:11Z",
        };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/whe_01jqr8x9zg5k2m3n4p5q6r7s8t/rotate-secret")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.endpoints.rotateSecret({
            webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("rotateSecret (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/webhook_endpoint_id/rotate-secret")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.rotateSecret({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("rotateSecret (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/webhook_endpoint_id/rotate-secret")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.rotateSecret({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.ForbiddenError);
    });

    test("rotateSecret (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/webhook_endpoint_id/rotate-secret")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.rotateSecret({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("rotateSecret (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/webhook_endpoint_id/rotate-secret")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.rotateSecret({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("rotateSecret (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints/webhook_endpoint_id/rotate-secret")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.rotateSecret({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("listDeliveries (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            next_cursor: "next_cursor",
            has_more: true,
            deliveries: [
                {
                    id: "whd_01krzmwm42h2hpk18sxc1hf937",
                    webhook_endpoint_id: "whe_01kwxwcbyb6wk952swa0432cf1",
                    event: "project.spend_budget.warning",
                    url: "url",
                    status: "pending",
                    attempt_count: 1,
                    last_attempt_at: "2024-01-15T09:30:00Z",
                    last_status_code: 1,
                    last_error: "last_error",
                    created_at: "2024-01-15T09:30:00Z",
                    request_body: "request_body",
                    request_headers: { key: "value" },
                    last_response_body: "last_response_body",
                    last_response_headers: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/webhooks/endpoints/whe_01jqr8x9zg5k2m3n4p5q6r7s8t/deliveries")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.webhooks.endpoints.listDeliveries({
            webhook_endpoint_id: "whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });

        expect(expected.deliveries).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.deliveries).toEqual(nextPage.data);
    });

    test("listDeliveries (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id/deliveries")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.listDeliveries({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("listDeliveries (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id/deliveries")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.listDeliveries({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("listDeliveries (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id/deliveries")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.listDeliveries({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("listDeliveries (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id/deliveries")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.listDeliveries({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("listDeliveries (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints/webhook_endpoint_id/deliveries")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.endpoints.listDeliveries({
                webhook_endpoint_id: "webhook_endpoint_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });
});
