// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
 *         slug: "acme-news",
 *         name: "Acme News"
 *     }
 */
export interface CreateHostedApiRequest {
    /**
     * A client-generated key (an opaque string, max 255 chars) that makes a
     * side-effect POST safe to retry: the server runs the operation exactly
     * once and replays the first response (its status and body) for 24 hours.
     * Reusing a key with a different request body, or while the first request
     * is still in flight, returns `409 idempotency_conflict`. A replayed
     * response carries the `Idempotent-Replayed: true` header.
     */
    "Idempotency-Key"?: string;
    /** 3-40 lowercase letters, digits or hyphens; a DNS label, unique on the shared domain; immutable. */
    slug: string;
    name: string;
    /** What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on. */
    description?: string;
    /** consumer_key when omitted. `public` is refused with 403 `hosted_api_public_refused` where the workspace's policy does not allow internet-facing APIs. */
    auth_mode?: CreateHostedApiRequest.AuthMode;
    cors_origins?: string[];
    /** Runs the API may start per UTC day through its run routes; 1000 when omitted. */
    daily_run_cap?: number;
    /** Reads the API's store, file, run_latest and tool routes may serve per UTC day; 100000 when omitted. */
    daily_read_cap?: number;
    /** Documents the API's write routes may land per UTC day; 10000 when omitted. */
    daily_write_cap?: number;
    /**
     * Serve the routes as an MCP server at `POST <base_url>/mcp` too;
     * false when omitted. Refused with `auth_mode: public` (400
     * `validation_failed` naming `mcp_enabled`).
     */
    mcp_enabled?: boolean;
    project_id?: string;
    /** Register the key set end-user tokens are verified against (an `https` URL on a public host). */
    user_token_jwks_url?: string;
}

export namespace CreateHostedApiRequest {
    /** consumer_key when omitted. `public` is refused with 403 `hosted_api_public_refused` where the workspace's policy does not allow internet-facing APIs. */
    export const AuthMode = {
        ConsumerKey: "consumer_key",
        Public: "public",
        UserToken: "user_token",
        Workspace: "workspace",
        Owner: "owner",
    } as const;
    export type AuthMode = (typeof AuthMode)[keyof typeof AuthMode];
}
