// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface GetOpenApiHostedApisRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
}
