// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "proj_01arz3ndektsv4rrffq69g5fav"
 *     }
 */
export interface ListHostedApisRequest {
    /** Opaque pagination cursor from a previous response. */
    cursor?: string;
    /** Max items per page (default 50, max 200). */
    limit?: number;
    /**
     * Filter by workspace project: omit for every project you can reach,
     * pass the literal `default` for resources in the implicit Default
     * project only, or a `proj_...` id for that project's resources.
     * Returns 404 project_not_found for a malformed id and for any filter
     * outside your reach: a project-pinned API key or service-account key
     * reaches only its pinned project, and a member holding project grants
     * reaches only the granted projects, so neither can name `default`.
     * That 404 is the same in every case and does not reveal whether such
     * a project exists - outside your reach a project is answered as
     * nonexistent, never as forbidden. Inside it, a well-formed id that
     * matches no project yields an empty page.
     */
    project_id?: string;
}
