// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
 *         api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface RotateUserTokenSecretHostedApisRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
    /**
     * A client-generated key (an opaque string, max 255 chars) that makes a
     * side-effect POST safe to retry: the server runs the operation exactly
     * once and replays the first response (its status and body) for 24 hours.
     * Reusing a key with a different request body, or while the first request
     * is still in flight, returns `409 idempotency_conflict`. A replayed
     * response carries the `Idempotent-Replayed: true` header.
     */
    "Idempotency-Key"?: string;
}
