// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface UpdateHostedApiRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
    name?: string;
    /** What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on. */
    description?: string;
    auth_mode?: UpdateHostedApiRequest.AuthMode;
    cors_origins?: string[];
    /** A paused API answers 503 to every consumer request. */
    enabled?: boolean;
    daily_run_cap?: number;
    daily_read_cap?: number;
    daily_write_cap?: number;
    /**
     * Switch the MCP face at `POST <base_url>/mcp` on or off. Refused with
     * 400 `validation_failed` naming `mcp_enabled` when the API is, or is
     * being made, `public`. Allow up to 15 seconds for the switch, like
     * any route change, to reach every server.
     */
    mcp_enabled?: boolean;
    /** Replace the registered key set; an empty string removes it, after which the signing secret verifies tokens again. */
    user_token_jwks_url?: string;
}

export namespace UpdateHostedApiRequest {
    export const AuthMode = {
        ConsumerKey: "consumer_key",
        Public: "public",
        UserToken: "user_token",
        Workspace: "workspace",
        Owner: "owner",
    } as const;
    export type AuthMode = (typeof AuthMode)[keyof typeof AuthMode];
}
