// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "proj_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface AuditProjectsRequest {
    /** Project id (prefixed external id, `proj_...`). */
    project_id: string;
    /** Opaque pagination cursor from a previous response. */
    cursor?: string;
    /** Max items per page (default 50, max 200). */
    limit?: number;
}
