// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Production"
 *     }
 */
export interface CreateProjectRequest {
    /**
     * Project name; unique per workspace (case-insensitive),
     * surrounding whitespace is trimmed.
     */
    name: string;
}
