// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "proj_01jqr8x9zg5k2m3n4p5q6r7s8t",
 *         mode: "purge",
 *         confirm: "Staging"
 *     }
 */
export interface DeleteProjectRequest {
    /** Project id (prefixed external id, `proj_...`). */
    project_id: string;
    /**
     * `detach` removes the grouping row only and moves every resource
     * to the Default project; `purge` removes the project with its
     * contents. Omitted, the delete removes only an empty project.
     */
    mode?: DeleteProjectRequest.Mode;
    /**
     * Required for `purge`: the project's name, exactly as returned by
     * GET. A mismatch answers 400 `validation_failed` naming this field.
     */
    confirm?: string;
}

export namespace DeleteProjectRequest {
    /**
     * `detach` removes the grouping row only and moves every resource
     * to the Default project; `purge` removes the project with its
     * contents. Omitted, the delete removes only an empty project.
     */
    export const Mode = {
        Detach: "detach",
        Purge: "purge",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
