// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "proj_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface GetProjectsRequest {
    /** Project id (prefixed external id, `proj_...`). */
    project_id: string;
}
