// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         api_id: "api_01kc4q3r9s6t8v0w2x4y6z8a0b",
 *         tool_id: "tool_01kc4n9s3v7w0y4a6c8e2g4j6m",
 *         name_prefix: "linear",
 *         dry_run: true
 *     }
 *
 * @example
 *     {
 *         api_id: "api_01kc4q3r9s6t8v0w2x4y6z8a0b",
 *         tool_id: "tool_01kc4n9s3v7w0y4a6c8e2g4j6m",
 *         name_prefix: "linear",
 *         operations: ["list_issues"],
 *         plan_digest: "ae5c24076805cfbad91442ca1ada6e79c2c246028b81e110ae9e4eab1f82dbce"
 *     }
 */
export interface MountHostedApiRoutesRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
    /**
     * A client-generated key (an opaque string, max 255 chars) that makes a
     * side-effect POST safe to retry: the server runs the operation exactly
     * once and replays the first response (its status and body) for 24 hours.
     * Reusing a key with a different request body, or while the first request
     * is still in flight, returns `409 idempotency_conflict`. A replayed
     * response carries the `Idempotent-Replayed: true` header.
     */
    "Idempotency-Key"?: string;
    /** The `openapi` or `mcp` tool definition to mount, in the API's project. */
    tool_id: string;
    /**
     * The operations to create routes for: openapi operation ids or the
     * MCP server's tool names. Omit to create a route for every operation
     * a route can serve. Naming one the connector does not offer is 400
     * `validation_failed` on `operations[i]`. Existing routes are compared
     * whatever the selection.
     */
    operations?: string[];
    /** Prefix of each created route's name, `<name_prefix>__<operation>`. Defaults to the tool's name with other characters as `_`. */
    name_prefix?: string;
    /** Path each created route sits under, `<path_prefix>/<operation>`; lowercase segments of letters, digits, `.`, `_` or `-`, with no `{param}` or `*`, and not under `/mcp`, `/openapi.json` or `/_runs`. Defaults to `/<name_prefix>` in lowercase. */
    path_prefix?: string;
    /** Answer what the mount would do and write nothing. */
    dry_run?: boolean;
    /**
     * Create routes for operations that are not reads too, each with
     * `allow_write: true`. Only an API whose `auth_mode` names a person
     * takes them; the operation's `approval` must still be `auto`.
     * Without it a write is a `skip` that says so.
     */
    include_writes?: boolean;
    /**
     * The `plan_digest` of the preview you reviewed. The apply writes
     * only while the plan it computes inside its transaction still has
     * this digest, and otherwise writes nothing and answers 409
     * `mount_plan_changed` with the current plan. Omit it to apply what
     * the mount plans now. Refused with `dry_run`.
     */
    plan_digest?: string;
}
