// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../../../../../../index.js";

/**
 * @example
 *     {
 *         api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
 *         route_id: "route_01jqr8x9zg5k2m3n4p5q6r7s8t"
 *     }
 */
export interface UpdateHostedApiRouteRequest {
    /** Hosted API id (prefixed external id, `api_...`). */
    api_id: string;
    /** Route id (prefixed external id, `route_...`). */
    route_id: string;
    method?: UpdateHostedApiRouteRequest.Method;
    path?: string;
    /**
     * The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
     * On an API with `mcp_enabled` the MCP tool's name comes from it:
     * each run of other characters (a space included) becomes `_`,
     * leading and trailing `_` are dropped, and the result is cut to 64
     * characters. A route with no name is listed under a name built from
     * its method and path, and a name two routes would share takes `_2`,
     * `_3` in route order; the face's `tools/list` is the authority. Pick
     * a verb-first name a model can choose by.
     */
    name?: string;
    /**
     * What the route does. On an API with `mcp_enabled` it is the MCP
     * tool description a client's model reads to choose the tool, so say
     * what it returns and when to call it; a `tool` route with none falls
     * back to the operation's summary.
     */
    description?: string;
    resolver?: Speechify.HostedApiResolver;
    response_schema?: Record<string, unknown> | null;
    cache_ttl_seconds?: number;
    enabled?: boolean;
}

export namespace UpdateHostedApiRouteRequest {
    export const Method = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
