// This file was auto-generated by Fern from our API Definition.

/**
 * Customer-facing per-tier limits + feature flags, including the API
 * rate limits the plan enforces. Numeric fields are caps; booleans gate
 * features.
 */
export interface BillingEntitlements {
    /** Members allowed in a single workspace (owner + invitees). */
    max_members: number;
    /**
     * Active service accounts allowed. 0 means service accounts are not
     * included in the plan (creating one returns 402
     * service_accounts_not_in_plan); existing accounts keep working.
     */
    max_service_accounts: number;
    /** Sustained requests per second across the audio (TTS) endpoints. */
    tts_requests_per_second: number;
    /** Simultaneous in-flight requests across the audio (TTS) endpoints. */
    tts_concurrency: number;
    /** Whether the workspace may create ADDITIONAL workspaces. */
    can_create_workspaces: boolean;
    /** Whether prepaid funds may be added beyond the monthly grant. */
    topup_allowed: boolean;
    /** Whether voice cloning is available. */
    voice_cloning: boolean;
    /** Whether Waymark API access is available. */
    waymark_access: boolean;
    /** Whether stores and hosted APIs are available. Off on every plan; granted per workspace. */
    hosted_apis_access: boolean;
    /** Documents one store may hold; 0 means uncapped. */
    max_store_documents: number;
    /** Bytes one store may hold across its documents; 0 means uncapped. */
    max_store_bytes: number;
    /** Whether enterprise SAML/OIDC SSO is available. */
    enterprise_sso: boolean;
    /**
     * Whether zero data retention is enabled for this workspace on the
     * Text to Speech API. Read-only: Speechify sets it against a signed
     * agreement, never self-serve, and that agreement defines the scope.
     */
    zero_data_retention: boolean;
    /**
     * Whether `POST /v1/voices` accepts a clone from this workspace
     * without a consent challenge and verification recording, because the
     * workspace captures and holds speaker consent under its own
     * agreement with Speechify. Read-only: Speechify sets it against that
     * agreement, never self-serve. It does not grant cloning - the
     * `voice_cloning` entitlement still applies.
     */
    voice_cloning_consent_exempt: boolean;
    /**
     * Largest single manual prepaid top-up accepted, in whole US dollars.
     * 0 means adding prepaid credit is not included in the plan. This is
     * the enforced amount, so a top-up of exactly this value succeeds; a
     * client may offer it directly without applying further bounds.
     */
    max_manual_top_up_usd: number;
    /**
     * Largest single automatic recharge, in whole US dollars. 0 means
     * auto-recharge is not included in the plan.
     */
    max_auto_recharge_charge_usd: number;
}
