// This file was auto-generated by Fern from our API Definition.

export interface ConsentChallenge {
    /**
     * Identifier for this challenge, sent back as `consent_challenge_id`
     * on the create. Treat it as an opaque string - the format is not part
     * of the contract and will not stay stable.
     */
    id: string;
    /**
     * The sentence the speaker must read aloud. Show it exactly as
     * returned - the recording is transcribed and matched against this
     * text, so re-wording, re-casing or re-punctuating it will fail the
     * check.
     */
    phrase: string;
    /**
     * When the challenge stops being usable. This is the only authority on
     * the window - do not hard-code a duration. Past it, create a new
     * challenge and record the new phrase.
     */
    expires_at: string;
}
