// This file was auto-generated by Fern from our API Definition.

export interface HostedApiUserTokenSecret {
    /** The plaintext signing secret, present on this response only. Sign end-user tokens with it (HS256). */
    secret: string;
    /** The masked form every later read shows as `user_token_secret_hint`. */
    secret_hint: string;
}
