// This file was auto-generated by Fern from our API Definition.

export interface HostedApiMountSummary {
    create: number;
    update: number;
    unchanged: number;
    skip: number;
    stale: number;
}
