// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface HostedApiMount {
    tool_id: string;
    tool_name: string;
    tool_kind: HostedApiMount.ToolKind;
    name_prefix: string;
    path_prefix: string;
    dry_run: boolean;
    /** One entry per operation the connector offers, in its order, then one per stale route whose operation it no longer offers. */
    operations: Speechify.HostedApiMountOperation[];
    summary: Speechify.HostedApiMountSummary;
    /**
     * Names this plan's content: every operation the connector offers and
     * every route the API holds for it, whatever `operations` selects,
     * and nothing that moves without the plan changing. Send it back as
     * the apply's `plan_digest` to write only this plan.
     */
    plan_digest: string;
}

export namespace HostedApiMount {
    export const ToolKind = {
        Openapi: "openapi",
        Mcp: "mcp",
    } as const;
    export type ToolKind = (typeof ToolKind)[keyof typeof ToolKind];
}
