// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface HostedApiMountOperation {
    operation: string;
    /** The operation's summary or description; the created route's description. */
    description: string;
    /** The operation's effective action class, or empty for a stale route whose operation is gone. */
    action_class: string;
    /** The operation's effective approval, or empty for a stale route whose operation is gone. */
    approval: string;
    /** Whether a route can serve it now (approval `auto`, and a read, or a write on a route with `allow_write` on an API that names a person). */
    servable: boolean;
    /** Whether the route serves a write: set on a create when the mount includes writes, and the existing route's own value otherwise. */
    allow_write: boolean;
    action: HostedApiMountOperation.Action;
    /** Why a `skip` or a `stale` entry is one, and what fixes it. */
    reason?: string | undefined;
    /** What an `update` rewrites. */
    changes?: HostedApiMountOperation.Changes.Item[] | undefined;
    /** The route's name, the MCP tool name the face lists. */
    name: string;
    path: string;
    route?: Speechify.HostedApiRoute | undefined;
}

export namespace HostedApiMountOperation {
    export const Action = {
        Create: "create",
        Update: "update",
        Unchanged: "unchanged",
        Skip: "skip",
        Stale: "stale",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
    export type Changes = Changes.Item[];

    export namespace Changes {
        export const Item = {
            InputSchema: "input_schema",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
