// This file was auto-generated by Fern from our API Definition.

export interface HostedApiUsage {
    /** The UTC day the counters cover, `YYYY-MM-DD`. */
    day: string;
    /** Reads served today across the API's store, file, run_latest and tool routes. */
    reads: number;
    daily_read_cap: number;
    /** Runs started today through the API's run routes. */
    runs: number;
    daily_run_cap: number;
    /** Documents landed today through the API's write routes. */
    writes: number;
    daily_write_cap: number;
    routes: HostedApiUsage.Routes.Item[];
    /** False where nothing counts (no Redis); the numbers are then zero, not quiet. */
    counters_available: boolean;
}

export namespace HostedApiUsage {
    export type Routes = Routes.Item[];

    export namespace Routes {
        export interface Item {
            route_id: string;
            reads: number;
            writes: number;
            /** For a `tool` route, the calls its connector was asked to answer today, whatever the outcome. */
            tool_calls?: number | undefined;
            /** For a `tool` route, today's calls the connector answered with an error or never answered (502 `route_upstream_error`). */
            upstream_errors?: number | undefined;
            /** For a `tool` route, today's calls throttled by the tool's `max_requests_per_minute` or by the connector (429 `route_upstream_rate_limited`). */
            upstream_throttles?: number | undefined;
            /** For a `tool` route, the mean time today's calls took, in milliseconds, connector included; null before the first call. A slow or failing connector shows here rather than as a slow API. */
            upstream_latency_ms_mean?: (number | null) | undefined;
        }
    }
}
