// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * What answers a route. `type` selects the fields that apply:
 * `store_query` (store_id, collection, where, order_by, limit),
 * `store_document` (store_id, collection, document_id),
 * `store_aggregate` (store_id, collection, where, group_by, metrics:
 * a summary in one request, from the same implementation as the
 * collection's `aggregate` operation),
 * `store_write` (store_id, collection, write_mode, document_id: the
 * request body lands as a document, the fast path past a run for the
 * one thing a read resolver cannot do; POST only, never on a public
 * API, and on an API that names its caller the document is that
 * person's),
 * `run_latest` (trigger_id of a schedule trigger),
 * `run` (trigger_id of a webhook trigger, wait_seconds),
 * `file` (file_path of one published file; or, on a route whose path
 * ends in `*`, file_root and file_index for a whole published tree),
 * `tool` (tool_id of an `openapi` or `mcp` tool definition and the
 * `operation` on it, an openapi operation's id or one of the MCP
 * server's tools by name: the POST body is the arguments, held to their
 * schema, and the connector's answer after the tool's response mapping
 * is the response. An openapi vendor's JSON comes back as it came, or
 * `{"text": ...}` when it answered text; an MCP tool answers its
 * structured content, its text when that text is JSON, `{"text": ...}`
 * for plain text, or `{"content": [...]}` with every block as the server
 * sent it when one is not text. For an `mcp` tool the route write lists
 * the server's tools and pins the chosen tool's input schema on the
 * route as `input_schema`, so the MCP face and every call use the pin
 * and an upstream change reaches no consumer until the route is written
 * again. An operation whose effective class is `read`, on a tool whose
 * `approval` is null or `auto`, may be served on any API but a public
 * one. An operation that is not a read is served only on a route with
 * `allow_write: true`, on an API whose `auth_mode` names a person
 * (`owner`, `workspace` or `user_token`), and still only with an
 * `approval` of null or `auto`: a write through a route acts for the
 * member or end user calling, who is sent to the connector as
 * `Speechify-User-Identity`, a service account is refused, every write
 * counts against `daily_write_cap` (429 `route_write_limit_reached`) and
 * claims the caller's `Idempotency-Key` so a retry replays the first
 * answer. A route write that breaks any of this is refused with 400
 * `validation_failed` on `resolver.tool_id`, `resolver.operation` or
 * `resolver.allow_write`, as is an MCP server that cannot be listed.
 * Because a definition can change after its route is written, every call
 * re-checks it: an operation no longer classified `read` on a route not
 * switched to writes, or a tool whose `approval` is no longer null or
 * `auto`, answers 403 `route_tool_not_readable`; a tool
 * deleted, moved to another project, or without the operation (an MCP
 * server that no longer lists the tool) answers 409
 * `route_tool_unavailable`, which no
 * retry clears until the route or the tool is fixed, and names which
 * of the three happened in `error.details.reason` (`tool_deleted`,
 * `tool_moved`, `operation_removed`). Both refusals carry what the API's
 * owner changes to fix the route in `error.details.fix`. Arguments that do
 * not fit the schema answer 400 `validation_failed`; the definition's
 * `max_requests_per_minute` and the vendor's own throttle both answer 429
 * `route_upstream_rate_limited` with `Retry-After`; a vendor error
 * answers 502 `route_upstream_error` with the vendor's status in
 * `error.details.upstream_status`, an MCP tool that reports an error
 * answers it with the tool's own message in `error.details.tool_error`,
 * and an unreachable vendor or a credential that no longer resolves
 * answers 502 `route_upstream_error` without either).
 */
export interface HostedApiResolver {
    type: HostedApiResolver.Type;
    store_id?: string | undefined;
    collection?: string | undefined;
    /** A literal id, a `{{path.x}}` / `{{query.x}}` / `{{body.x}}` template bound from the request, or a `{{user.x}}` claim of the verified caller. On a `store_write` route it names the document a replace or merge lands on, and is refused on a create. */
    document_id?: string | undefined;
    /**
     * For a `store_write` route: `create` mints an id and answers 201
     * with the document; `replace` and `merge` land on `document_id`
     * (a merge sets the fields sent and keeps the rest) and answer 200.
     * Omitted, a route with a document_id merges and one without
     * creates. On an API that names its caller, a replace or merge of
     * another person's document is not found.
     */
    write_mode?: HostedApiResolver.WriteMode | undefined;
    where?: HostedApiResolver.Where.Item[] | undefined;
    order_by?: HostedApiResolver.OrderBy | undefined;
    /** Default page size; the consumer's `limit` query parameter overrides it. */
    limit?: number | undefined;
    /** For a `store_aggregate` route, the projected field to group by. */
    group_by?: string | undefined;
    /** For a `store_aggregate` route, the reductions to answer with; the where clauses bind from the request as on a query. */
    metrics?: Speechify.StoreAggregateMetric[] | undefined;
    /**
     * The path a `kept` file was published under, for a `file` route on
     * a path without a wildcard. The route answers that file's bytes
     * under the file's own media type - the only route type that does
     * not return JSON - so a page renders and a spreadsheet downloads.
     * Must be a GET.
     *
     * A literal path, or a `{{path.x}}` template that replaces the whole
     * value and binds one segment of the URL. A template embedded in a
     * longer path (`a/{{path.x}}.html`) is refused - substitution here
     * replaces the value, it does not interpolate into it. To serve many
     * files, or a nested tree, mount a route ending in `*` and use
     * file_root instead.
     *
     * Only a `kept`, workspace-wide file is reachable: working material
     * handed to a run cannot be published by pointing a route at it, and
     * a file uploaded for one person is never served by a route, because
     * a route answers whoever holds the URL. A `{{user.x}}` template may
     * shape the path on a `user_token` API, but the file it reaches is
     * still one the workspace published. A path with nothing at it
     * answers `404`, so an artifact can be wired before it is uploaded
     * and replaced without touching the route.
     */
    file_path?: string | undefined;
    /**
     * For a `file` route whose path ends in `*`: the published-path
     * prefix the tree lives under (`dash` serves `dash/index.html` at
     * `/app/index.html` on a route at `/app/*`). Empty serves every
     * published file under the route. A rebuild that renames the tree's
     * assets touches no route. Refused on a route without the wildcard.
     */
    file_root?: string | undefined;
    /**
     * For a tree route: the entry document, relative to file_root, that
     * a bare prefix answers and that an unmatched path with no file
     * extension falls back to, so a client-routed application survives
     * a refresh and a deep link. A missing asset with an extension stays
     * a 404. Omit for a plain file tree.
     */
    file_index?: string | undefined;
    trigger_id?: string | undefined;
    /** How long a `run` route waits for the run before answering 202 (default 20; 0 answers 202 at once). */
    wait_seconds?: number | undefined;
    /**
     * For a `tool` route: the `openapi` or `mcp` tool definition whose
     * operation the route calls, as `POST /v1/agents/tool-definitions`
     * returned it. It must live in the API's project (409
     * `cross_project_reference` otherwise). The route refuses a definition
     * of another kind, an operation whose effective class is not `read`,
     * and a tool whose `approval` is set to anything but `auto`, since a
     * route has nobody to approve a call: set it to null or `auto` first.
     */
    tool_id?: string | undefined;
    /**
     * For a `tool` route: the operation to call. On an `openapi` tool it
     * is the definition's `operations[].id` (the same value
     * `POST /v1/agents/tool-definitions/test-openapi-call` takes as
     * `operation`); on an `mcp` tool it is the server's own tool name,
     * as `POST /v1/agents/tool-definitions/test-mcp-connection` lists
     * it. The route is a POST whose JSON body is the arguments, validated
     * against the definition's argument schema for an openapi operation
     * and against `input_schema` for an MCP tool.
     */
    operation?: string | undefined;
    /**
     * For a `tool` route: serve an operation that is not a read (refused
     * on an operation that is one). Only on
     * an API whose `auth_mode` is `owner`, `workspace` or `user_token`,
     * and only for an operation whose effective `approval` is `auto`;
     * the API cannot then be switched to `consumer_key` or `public`
     * while the route serves writes. A write acts for the person
     * calling, counts against `daily_write_cap`, and claims
     * `Idempotency-Key`. On the MCP face the tool is not read-only.
     */
    allow_write?: boolean | undefined;
    /**
     * For a `tool` route on an `mcp` tool: the MCP tool's input schema
     * as the server listed it when the route was last written, pinned so
     * the MCP face lists it and every call is checked against it without
     * reaching the server. Set by the platform on every write that
     * carries a resolver; a value you send is replaced. Absent on an
     * openapi route, whose schema the definition holds. Write the route
     * again to pick up a schema the server changed.
     */
    input_schema?: Record<string, unknown> | undefined;
}

export namespace HostedApiResolver {
    export const Type = {
        StoreQuery: "store_query",
        StoreDocument: "store_document",
        StoreAggregate: "store_aggregate",
        StoreWrite: "store_write",
        RunLatest: "run_latest",
        Run: "run",
        File: "file",
        Tool: "tool",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /**
     * For a `store_write` route: `create` mints an id and answers 201
     * with the document; `replace` and `merge` land on `document_id`
     * (a merge sets the fields sent and keeps the rest) and answer 200.
     * Omitted, a route with a document_id merges and one without
     * creates. On an API that names its caller, a replace or merge of
     * another person's document is not found.
     */
    export const WriteMode = {
        Create: "create",
        Replace: "replace",
        Merge: "merge",
    } as const;
    export type WriteMode = (typeof WriteMode)[keyof typeof WriteMode];
    export type Where = Where.Item[];

    export namespace Where {
        export interface Item {
            field: string;
            op: Item.Op;
            value?: unknown | undefined;
        }

        export namespace Item {
            export const Op = {
                Eq: "eq",
                Ne: "ne",
                Gt: "gt",
                Gte: "gte",
                Lt: "lt",
                Lte: "lte",
                In: "in",
            } as const;
            export type Op = (typeof Op)[keyof typeof Op];
        }
    }

    export interface OrderBy {
        field: string;
        direction?: OrderBy.Direction | undefined;
    }

    export namespace OrderBy {
        export const Direction = {
            Asc: "asc",
            Desc: "desc",
        } as const;
        export type Direction = (typeof Direction)[keyof typeof Direction];
    }
}
