// This file was auto-generated by Fern from our API Definition.

export interface HostedApiKey {
    id: string;
    api_id: string;
    name: string;
    /** The masked secret shown on every read. */
    key_hint: string;
    /** Requests per minute this key may make; 0 is unlimited. */
    rate_per_minute: number;
    /** The plaintext key, present on the create response only. */
    secret?: string | undefined;
    revoked_at?: string | undefined;
    last_used_at?: string | undefined;
    created_at: string;
}
