// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface HostedApiRoute {
    id: string;
    api_id: string;
    method: HostedApiRoute.Method;
    /** Lowercase segments, one-segment `{params}`, and optionally a trailing `*` that serves a published tree (file routes only). */
    path: string;
    /**
     * The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
     * On an API with `mcp_enabled` the MCP tool's name comes from it:
     * each run of other characters (a space included) becomes `_`,
     * leading and trailing `_` are dropped, and the result is cut to 64
     * characters. A route with no name is listed under a name built from
     * its method and path, and a name two routes would share takes `_2`,
     * `_3` in route order; the face's `tools/list` is the authority. Pick
     * a verb-first name a model can choose by.
     */
    name: string;
    /**
     * What the route does. On an API with `mcp_enabled` it is the MCP
     * tool description a client's model reads to choose the tool, so say
     * what it returns and when to call it; a `tool` route with none falls
     * back to the operation's summary.
     */
    description: string;
    resolver: Speechify.HostedApiResolver;
    /** Optional JSON Schema of the response body, rendered into the OpenAPI document. */
    response_schema?: Record<string, unknown> | undefined;
    /**
     * Cache-Control max-age on GET responses, and the shared response
     * cache's lifetime for store and run_latest routes; 0 disables
     * caching, except on a public API, where a GET route with 0 is served
     * with the platform default of 60 seconds so an anonymous crawler
     * never reads storage per request. File routes are never in the
     * response cache; they carry the header for the edge.
     */
    cache_ttl_seconds: number;
    enabled: boolean;
    created_at: string;
    updated_at: string;
}

export namespace HostedApiRoute {
    export const Method = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
