// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * Payload for GET /v1/webhooks/endpoints/{webhook_endpoint_id}/deliveries.
 */
export interface ListWebhookEndpointDeliveriesResponse extends Speechify.PaginationMeta {
    deliveries: Speechify.WebhookEndpointDelivery[];
}
