// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface ListHostedApiRoutesResponse extends Speechify.PaginationMeta {
    routes: Speechify.HostedApiRoute[];
}
