// This file was auto-generated by Fern from our API Definition.

/**
 * What the restore deliberately left revoked: the credentials the purge
 * killed. Every field is a real count, including zero.
 */
export interface ProjectStillRevokedCounts {
    api_keys?: number | undefined;
    service_accounts?: number | undefined;
    credentials?: number | undefined;
    webhook_endpoints?: number | undefined;
}
