// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * The outcome of restoring a purged project: what deliberately did not
 * come back.
 *
 * `still_revoked` counts the credentials the purge revoked and this
 * call left revoked, because re-issuing a credential someone killed
 * would hand back access rather than restore a project. Member grants
 * and pending-invite scopes are in that group too, but their rows were
 * removed by the purge, so they cannot be counted and appear only in
 * `not_restored_note`.
 *
 * The project comes back ARCHIVED, the state it was purged from, so
 * `archived_at` is always set: nothing dispatches or bills inside it
 * until you unarchive it on purpose.
 */
export interface ProjectRestore {
    id?: string | undefined;
    name?: string | undefined;
    /** When the purge this call walked back happened. */
    purged_at?: string | undefined;
    /**
     * When the project was archived. Always set on a restore: a project
     * comes back suspended, never live.
     */
    archived_at?: (string | null) | undefined;
    still_revoked?: Speechify.ProjectStillRevokedCounts | undefined;
    /**
     * A plain-language statement of what a restore does not bring back.
     * Constant text, meant to be shown to a person; branch on
     * `still_revoked` rather than parsing it.
     */
    not_restored_note?: string | undefined;
}
