// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface ProjectMembersResponse extends Speechify.PaginationMeta {
    members: Speechify.ProjectMember[];
}
