// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * One page of a project's audit trail, newest change first.
 */
export interface ProjectAuditResponse extends Speechify.PaginationMeta {
    events: Speechify.ProjectAuditEvent[];
}
