// This file was auto-generated by Fern from our API Definition.

/**
 * One change to this project's access or lifecycle state. The subject is
 * whose access changed; the actor is who changed it.
 *
 * Every field below is always present. A field the event did not carry is
 * `null`, which is a different fact from the key being absent altogether:
 * `null` means this event had no such party, an absent key would mean the
 * entry predates the platform recording that party at all. Audit entries
 * are never backfilled, so the two are kept distinct.
 */
export interface ProjectAuditEvent {
    /** When the change was recorded. */
    time: string;
    /**
     * What changed. `access_widened_to_workspace` is the revoke that
     * removed the subject's LAST grant anywhere: a member with no grants
     * reaches the whole workspace, so that revoke widened them rather
     * than narrowing them.
     */
    type: ProjectAuditEvent.Type;
    /** The member whose access changed. Null on a lifecycle change, which is done to the project rather than to a person. */
    subject_user_id?: (string | null) | undefined;
    /** The member who made the change. Null when the change was system-initiated. */
    actor_user_id?: (string | null) | undefined;
    /** The actor's email at the time of the change. Null when the change carried no email. */
    actor_email?: (string | null) | undefined;
    /** The workspace role the actor held at the time. A role read back today cannot answer what they held when they acted. Null when the change carried no role. */
    actor_role?: (string | null) | undefined;
    /** The Speechify support admin acting on the workspace's behalf. Null unless the change came through support. */
    impersonator_email?: (string | null) | undefined;
    /** How many projects the subject held after the change. Null on a lifecycle change; zero is what makes a revoke a widening to the whole workspace. */
    remaining_grants?: (number | null) | undefined;
}

export namespace ProjectAuditEvent {
    /**
     * What changed. `access_widened_to_workspace` is the revoke that
     * removed the subject's LAST grant anywhere: a member with no grants
     * reaches the whole workspace, so that revoke widened them rather
     * than narrowing them.
     */
    export const Type = {
        AccessGranted: "access_granted",
        AccessRevoked: "access_revoked",
        AccessWidenedToWorkspace: "access_widened_to_workspace",
        Archived: "archived",
        Unarchived: "unarchived",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
