// This file was auto-generated by Fern from our API Definition.

/**
 * One project grant - a workspace member who may reach this project.
 */
export interface ProjectMember {
    /** The member's prefixed user id, joinable to the workspace members list. */
    user_id: string;
    created_at: string;
    /** The prefixed user id of whoever made the grant. Attribution only. */
    granted_by: string;
}
