// This file was auto-generated by Fern from our API Definition.

/**
 * One granularity bucket of the request analytics series.
 */
export interface RequestAnalyticsBucket {
    /** Start of the bucket. */
    time: string;
    requests: number;
    errors: number;
    server_errors: number;
    success_rate: number;
    avg_latency_ms: number;
    p50_latency_ms: number;
    p95_latency_ms: number;
    p99_latency_ms: number;
    /**
     * How many of `requests` were streaming synthesis (`POST
     * /v1/audio/stream`) and so reported a time-to-first-byte. Every other
     * route leaves the `p*_ttfb_ms` fields meaningless; when this is 0,
     * render a gap rather than a zero.
     */
    ttfb_requests: number;
    /** Median time to first byte over the bucket's streaming requests. */
    p50_ttfb_ms: number;
    /**
     * 95th-percentile time to first byte over the bucket's streaming
     * requests. This is also time to first *audio*: the streaming response
     * body is raw audio, so the first byte is the first audio byte.
     * Scoped to streaming on purpose. `POST /v1/audio/speech` returns the
     * whole audio Base64-encoded in one JSON response, so its TTFB is its
     * total latency (already reported as `p*_latency_ms`) and blending the
     * two would describe neither.
     */
    p95_ttfb_ms: number;
    /** 99th-percentile time to first byte over the bucket's streaming requests. */
    p99_ttfb_ms: number;
}
