// This file was auto-generated by Fern from our API Definition.

/**
 * Window-wide rollups.
 */
export interface RequestAnalyticsTotals {
    /** Total requests in the window. */
    requests: number;
    /** Responses with a 4xx or 5xx status. */
    errors: number;
    /** Responses with a 5xx status. */
    server_errors: number;
    /** Share of non-error responses, 0..1. */
    success_rate: number;
    /** Requests in the window that carried a Speechify SDK identity header, a subset of `requests`. Zero means no SDK traffic, which is a real answer rather than missing data. */
    sdk_requests: number;
}
