// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * Aggregate request analytics over a window of the request log.
 */
export interface RequestAnalyticsResponse {
    /** The time-bucket size of the series. */
    granularity: string;
    /** Inclusive start of the resolved window. */
    start: string;
    /** Exclusive end of the resolved window. */
    end: string;
    totals: Speechify.RequestAnalyticsTotals;
    /** Per-bucket time series, oldest first. */
    series: Speechify.RequestAnalyticsBucket[];
    /** The most-called route patterns in the window, busiest first. */
    top_paths: Speechify.RequestTopPath[];
    /** True when a `project_id` filter's pinned key set exceeded the cap this endpoint applies: the result reflects only the project's newest keys within the cap, not its full traffic. Omitted (false) when no project filter was requested or its key set fit under the cap. */
    project_filter_truncated?: boolean | undefined;
    /** Hosted API analytics only: the first request in the last 30 days the request log attributes to this API. Requests before it cannot be attributed, so a bucket before it is missing data rather than zero traffic. Absent when no such request exists, in which case no bucket is known to be complete. */
    history_starts_at?: string | undefined;
}
