// This file was auto-generated by Fern from our API Definition.

/**
 * A stable, opaque identifier for the end user of your application on whose behalf this request is made. Use it when many of your own users share one Speechify workspace, for example behind a gateway, a reseller or a consumer app.
 *
 * Send a hash of your internal user id (for example a hex or base64 SHA-256), or an opaque id that means nothing outside your system. Never send an email address, a name, a phone number or any other personal data: the field accepts only letters, digits and `. _ - : | + / =`, so an email address is refused with `400 validation_failed`.
 *
 * The identifier is request metadata, not content. It is recorded with the request even when your workspace has zero data retention, so abuse can be attributed to one end user rather than to your whole workspace. When your workspace has per-end-user limits, it also has its own rate and concurrency allowance inside the workspace's (`429` with a message naming the `safety_identifier`), and a blocked identifier is refused with `403 safety_identifier_blocked` while your other end users are unaffected. Omitting it changes nothing. See https://docs.speechify.ai/build/guides/concepts/safety-identifiers.
 */
export type SafetyIdentifier = string;
