// This file was auto-generated by Fern from our API Definition.

/**
 * Terminal event: the synthesis completed and no further events follow.
 * There is no `[DONE]` sentinel.
 */
export interface SpeechDoneEvent {
    /** Number of billable characters processed. */
    billable_characters_count: number;
    /** Duration of the synthesized audio in milliseconds. */
    audio_duration_ms: number;
}
