// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * A run of synthesized audio, the speech marks that became final with it,
 * or both - a chunk may carry only one of the two, and the last chunk of
 * a stream is often marks-only. Mark times are absolute milliseconds from
 * the start of the synthesis: concatenate the audio chunks into one
 * stream and apply the marks against that single timeline. Which chunk a
 * mark arrives on is a delivery detail and carries no meaning.
 */
export interface SpeechChunkEvent {
    /**
     * A run of the synthesized audio, Base64-encoded, in the format the
     * request selected (echoed on the `Speechify-Audio-Content-Type`
     * response header). Absent on a marks-only chunk.
     */
    audio?: string | undefined;
    /**
     * Word timings addressing the original input text, with absolute
     * millisecond times from the start of the synthesis. Absent when the
     * chunk carries only audio.
     */
    speech_marks?: Speechify.NestedChunk[] | undefined;
}
