// This file was auto-generated by Fern from our API Definition.

export interface StoreAggregateMetric {
    op: StoreAggregateMetric.Op;
    /** The projected numeric field to reduce; `count` takes none. A document whose field is absent or not a number is left out of that metric. */
    field?: string | undefined;
    /** The key the metric answers under; `op` or `op_field` when omitted. */
    as?: string | undefined;
}

export namespace StoreAggregateMetric {
    export const Op = {
        Count: "count",
        Sum: "sum",
        Avg: "avg",
        Min: "min",
        Max: "max",
    } as const;
    export type Op = (typeof Op)[keyof typeof Op];
}
