// This file was auto-generated by Fern from our API Definition.

/**
 * The verification answer for one clip.
 *
 * One field, and no confidence score: a score is a gradient, and a public
 * gradient turns "does this carry the mark" into "adjust the clip until
 * the number drops". Use `POST /v1/audio/watermark/detect` if you need it.
 *
 * `watermarked: true` is positive evidence the audio came from Speechify
 * synthesis. `watermarked: false` is the absence of that evidence, not
 * proof of a negative - see the endpoint description.
 */
export interface WatermarkVerificationResponse {
    /** Whether the clip carries the Speechify watermark. */
    watermarked: boolean;
}
