// This file was auto-generated by Fern from our API Definition.

/**
 * The watermark detector's answer for one clip.
 *
 * `watermarked: true` is positive evidence the audio came from Speechify
 * synthesis. `watermarked: false` is the absence of that evidence, not
 * proof of a negative - see the endpoint description for the three reasons
 * genuinely Speechify-generated audio can come back unmarked.
 */
export interface WatermarkDetectionResponse {
    /**
     * Whether the clip carries the watermark, i.e. whether `confidence`
     * cleared the service's configured bar.
     */
    watermarked: boolean;
    /**
     * The detector's score for this clip, in [0, 1]. Comparable only
     * between checks made against the same detector version.
     */
    confidence: number;
}
