// This file was auto-generated by Fern from our API Definition.

/**
 * Lifecycle of a webhook delivery row. The sender updates the same row
 * across retries, so a read always sees the latest outcome.
 */
export const WebhookDeliveryStatus = {
    Pending: "pending",
    Delivered: "delivered",
    Failed: "failed",
} as const;
export type WebhookDeliveryStatus = (typeof WebhookDeliveryStatus)[keyof typeof WebhookDeliveryStatus];
