// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * One row of an endpoint's delivery log. One row per (endpoint, event,
 * resource); updated in place across retry attempts. Each row records the
 * exact request payload + signed headers Speechify sent and the response
 * your server returned, so you can verify the signature and debug failures.
 */
export interface WebhookEndpointDelivery {
    /** Prefixed delivery id (`whd_<26 char Crockford base32>`). */
    id: string;
    /** The endpoint this delivery targeted (`whe_…`). */
    webhook_endpoint_id: string;
    /** The event type delivered (see `WebhookEventType`). */
    event: string;
    /** The destination URL at delivery time. */
    url: string;
    status: Speechify.WebhookDeliveryStatus;
    attempt_count: number;
    last_attempt_at?: string | undefined;
    last_status_code?: number | undefined;
    last_error?: string | undefined;
    created_at: string;
    /**
     * The verbatim payload the `Speechify-Signature` HMAC was computed over
     * (as `<t>.<raw_body>`).
     */
    request_body?: string | undefined;
    /** Headers sent, including `Speechify-Signature` / `Speechify-Event` / `Speechify-Delivery-Id`. */
    request_headers?: Record<string, string> | undefined;
    /** Your server's response body on the most recent attempt (truncated to 8 KiB). */
    last_response_body?: string | undefined;
    last_response_headers?: Record<string, string> | undefined;
}
