// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { EndpointsClient } from "../resources/endpoints/client/Client.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;
    protected _endpoints: EndpointsClient | undefined;

    constructor(options: WebhooksClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get endpoints(): EndpointsClient {
        return (this._endpoints ??= new EndpointsClient(this._options));
    }
}
