// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../core/index.js";

/**
 * @example
 *     {
 *         audio: fs.createReadStream("/path/to/your/file")
 *     }
 */
export interface DetectWatermarkRequest {
    /**
     * The clip to check, at most 25MB. Give the detector at least
     * three seconds of clear speech; below that its confidence is
     * not worth acting on, and below half a second it always
     * reports zero.
     */
    audio: core.file.Uploadable;
}
