// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../core/index.js";

/**
 * @example
 *     {
 *         audio: fs.createReadStream("/path/to/your/file")
 *     }
 */
export interface VerifyWatermarkRequest {
    /**
     * The clip to check, at most 25MB. Give the detector at least
     * three seconds of clear speech; below that its answer is not
     * worth acting on.
     */
    audio: core.file.Uploadable;
}
