// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../../../../index.js";

/**
 * @example
 *     {
 *         locale: "en",
 *         model: "simba-3.2"
 *     }
 */
export interface ListVoicesRequest {
    /** Opaque pagination cursor from a previous response. */
    cursor?: string;
    /** Max items per page (default 50, max 200). */
    limit?: number;
    /**
     * Filter by voice type: `personal` (the workspace's cloned voices)
     * or `shared` (the public catalogue). Omit to return both.
     */
    type?: Speechify.ListVoicesRequestType;
    /**
     * Filter to voices whose locale matches this BCP-47 language range,
     * prefix-matched: `en` matches `en-US` and `en-GB`; `en-US` matches
     * only `en-US`. Case-insensitive. Omit to return all locales.
     */
    locale?: string;
    /** Filter by voice gender. Omit to return all genders. */
    gender?: Speechify.ListVoicesRequestGender;
    /**
     * Filter to voices that support this model (as listed in each voice's
     * `models[]`), e.g. `simba-3.2`. Omit to return voices for all models.
     */
    model?: string;
}
