// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../../../../index.js";

/**
 * @example
 *     {
 *         locale: "en",
 *         model: "simba-3.2",
 *         project_id: "proj_01arz3ndektsv4rrffq69g5fav"
 *     }
 */
export interface ListVoicesRequest {
    /** Opaque pagination cursor from a previous response. */
    cursor?: string;
    /** Max items per page (default 50, max 200). */
    limit?: number;
    /**
     * Filter by voice type: `personal` (the workspace's cloned voices)
     * or `shared` (the public catalogue). Omit to return both.
     */
    type?: Speechify.ListVoicesRequestType;
    /**
     * Filter to voices whose locale matches this BCP-47 language range,
     * prefix-matched: `en` matches `en-US` and `en-GB`; `en-US` matches
     * only `en-US`. Case-insensitive. Omit to return all locales.
     */
    locale?: string;
    /** Filter by voice gender. Omit to return all genders. */
    gender?: Speechify.ListVoicesRequestGender;
    /**
     * Filter to voices that support this model (as listed in each voice's
     * `models[]`), e.g. `simba-3.2`. Omit to return voices for all models.
     */
    model?: string;
    /**
     * Filter cloned voices by workspace project: omit for every voice you
     * can reach, or pass a `proj_...` id to list the clones filed under
     * that project. The shared catalog carries no project and is returned
     * either way.
     *
     * A clone is filed under a project when a project-pinned key created
     * it; a clone with no project belongs to the workspace at large, so
     * there is no `default` literal here - passing one is a 400. Returns
     * 404 project_not_found for a malformed id and for any project outside
     * your reach: a project-pinned key reaches only its pinned project,
     * and a member holding project grants reaches only the granted ones.
     * That 404 is the same in every case and does not reveal whether such
     * a project exists.
     */
    project_id?: string;
}
