// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             input: "Streaming long-form audio with the Speechify API.",
 *             model: "simba-3.2",
 *             voice_id: "geffen_32"
 *         }
 *     }
 */
export interface StreamWithTimestampsAudioRequest {
    /**
     * Selects the audio container/codec carried inside the events when
     * `output_format` is not set in the request body. The selected media
     * type is echoed on the `Speechify-Audio-Content-Type` response
     * header, since the response's own Content-Type is `text/event-stream`.
     */
    Accept?: Speechify.StreamWithTimestampsAudioRequestAccept;
    body: Speechify.GetStreamRequest;
}
