// This file was auto-generated by Fern from our API Definition.

import * as Speechify from "../../src/api/index";
import { SpeechifyClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HostedApisClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            next_cursor: "next_cursor",
            has_more: true,
            apis: [
                {
                    id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                    slug: "acme-news",
                    hostname: "acme-news.apis.speechify.ai",
                    base_url: "https://acme-news.apis.speechify.ai",
                    name: "name",
                    description: "description",
                    auth_mode: "consumer_key",
                    cors_origins: ["cors_origins"],
                    enabled: true,
                    daily_run_cap: 1,
                    daily_read_cap: 1,
                    daily_write_cap: 1,
                    mcp_enabled: false,
                    mcp_url: "https://acme-tools.apis.speechify.ai/mcp",
                    project_id: "project_id",
                    user_token_jwks_url: "user_token_jwks_url",
                    user_token_secret_hint: "uts_••••wxyz",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/apis")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.hostedApis.list({
            project_id: "proj_01arz3ndektsv4rrffq69g5fav",
        });

        expect(expected.apis).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.apis).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.list();
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "acme-news", name: "Acme News" };
        const rawResponseBody = {
            id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            slug: "acme-news",
            hostname: "acme-news.apis.speechify.ai",
            base_url: "https://acme-news.apis.speechify.ai",
            name: "name",
            description: "description",
            auth_mode: "consumer_key",
            cors_origins: ["cors_origins"],
            enabled: true,
            daily_run_cap: 1,
            daily_read_cap: 1,
            daily_write_cap: 1,
            mcp_enabled: false,
            mcp_url: "https://acme-tools.apis.speechify.ai/mcp",
            project_id: "project_id",
            user_token_jwks_url: "user_token_jwks_url",
            user_token_secret_hint: "uts_••••wxyz",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .header("Idempotency-Key", "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.create({
            "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            slug: "acme-news",
            name: "Acme News",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { slug: "slug", name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.create({
                slug: "slug",
                name: "name",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            slug: "acme-news",
            hostname: "acme-news.apis.speechify.ai",
            base_url: "https://acme-news.apis.speechify.ai",
            name: "name",
            description: "description",
            auth_mode: "consumer_key",
            cors_origins: ["cors_origins"],
            enabled: true,
            daily_run_cap: 1,
            daily_read_cap: 1,
            daily_write_cap: 1,
            mcp_enabled: false,
            mcp_url: "https://acme-tools.apis.speechify.ai/mcp",
            project_id: "project_id",
            user_token_jwks_url: "user_token_jwks_url",
            user_token_secret_hint: "uts_••••wxyz",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.get({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().get("/v1/apis/api_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.get({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t").respondWith().statusCode(200).build();

        const response = await client.hostedApis.delete({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server.mockEndpoint().delete("/v1/apis/api_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hostedApis.delete({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            slug: "acme-news",
            hostname: "acme-news.apis.speechify.ai",
            base_url: "https://acme-news.apis.speechify.ai",
            name: "name",
            description: "description",
            auth_mode: "consumer_key",
            cors_origins: ["cors_origins"],
            enabled: true,
            daily_run_cap: 1,
            daily_read_cap: 1,
            daily_write_cap: 1,
            mcp_enabled: false,
            mcp_url: "https://acme-tools.apis.speechify.ai/mcp",
            project_id: "project_id",
            user_token_jwks_url: "user_token_jwks_url",
            user_token_secret_hint: "uts_••••wxyz",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.update({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/apis/api_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.update({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("getOpenApi (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/openapi")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.getOpenApi({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOpenApi (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("getOpenApi (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("getOpenApi (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("getOpenApi (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("getOpenApi (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("getOpenApi (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/openapi")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getOpenApi({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("getUsage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            day: "2026-09-09",
            reads: 1000000,
            daily_read_cap: 1,
            runs: 1000000,
            daily_run_cap: 1,
            writes: 1000000,
            daily_write_cap: 1,
            routes: [
                {
                    route_id: "route_id",
                    reads: 1000000,
                    writes: 1000000,
                    tool_calls: 1000000,
                    upstream_errors: 1000000,
                    upstream_throttles: 1000000,
                    upstream_latency_ms_mean: 1000000,
                },
            ],
            counters_available: true,
        };

        server
            .mockEndpoint()
            .get("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/usage")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.getUsage({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getUsage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("getUsage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("getUsage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("getUsage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("getUsage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("getUsage (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/usage")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getUsage({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("getAnalytics (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            granularity: "1h",
            start: "2024-01-15T09:30:00Z",
            end: "2024-01-15T09:30:00Z",
            totals: { requests: 1, errors: 1, server_errors: 1, success_rate: 0.985, sdk_requests: 412 },
            series: [
                {
                    time: "2024-01-15T09:30:00Z",
                    requests: 1,
                    errors: 1,
                    server_errors: 1,
                    success_rate: 1.1,
                    avg_latency_ms: 1.1,
                    p50_latency_ms: 1.1,
                    p95_latency_ms: 1.1,
                    p99_latency_ms: 1.1,
                    ttfb_requests: 1,
                    p50_ttfb_ms: 1.1,
                    p95_ttfb_ms: 1.1,
                    p99_ttfb_ms: 1.1,
                },
            ],
            top_paths: [{ route: "/v1/audio/speech", count: 1, route_id: "route_01jqr8x9zg5k2m3n4p5q6r7s8t" }],
            project_filter_truncated: true,
            history_starts_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/analytics")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.getAnalytics({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            start: "2026-06-23T00:00:00Z",
            end: "2026-06-30T00:00:00Z",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAnalytics (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("getAnalytics (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("getAnalytics (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("getAnalytics (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("getAnalytics (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("getAnalytics (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("getAnalytics (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadGatewayError);
    });

    test("getAnalytics (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/analytics")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.getAnalytics({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.ServiceUnavailableError);
    });

    test("rotateUserTokenSecret (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { secret: "uts_kf93Ls0pQ...", secret_hint: "uts_••••wxyz" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/rotate-user-token-secret")
            .header("Idempotency-Key", "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.rotateUserTokenSecret({
            "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("rotateUserTokenSecret (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("rotateUserTokenSecret (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("rotateUserTokenSecret (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("rotateUserTokenSecret (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("rotateUserTokenSecret (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("rotateUserTokenSecret (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/rotate-user-token-secret")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.rotateUserTokenSecret({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });
});
