// This file was auto-generated by Fern from our API Definition.

import * as Speechify from "../../src/api/index";
import { SpeechifyClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WorkspacesClient", () => {
    test("getEntitlements (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            catalog: {
                pro: {
                    max_members: 1,
                    max_service_accounts: 50,
                    tts_requests_per_second: 20,
                    tts_concurrency: 15,
                    can_create_workspaces: true,
                    topup_allowed: true,
                    voice_cloning: true,
                    waymark_access: false,
                    hosted_apis_access: true,
                    max_store_documents: 1,
                    max_store_bytes: 1000000,
                    enterprise_sso: false,
                    zero_data_retention: true,
                    voice_cloning_consent_exempt: true,
                    max_manual_top_up_usd: 1,
                    max_auto_recharge_charge_usd: 1,
                },
            },
            current: {
                max_members: 1,
                max_service_accounts: 50,
                tts_requests_per_second: 20,
                tts_concurrency: 15,
                can_create_workspaces: true,
                topup_allowed: true,
                voice_cloning: true,
                waymark_access: false,
                hosted_apis_access: true,
                max_store_documents: 1,
                max_store_bytes: 1000000,
                enterprise_sso: false,
                zero_data_retention: true,
                voice_cloning_consent_exempt: true,
                max_manual_top_up_usd: 1,
                max_auto_recharge_charge_usd: 1,
            },
        };

        server
            .mockEndpoint()
            .get("/v1/workspaces/current/entitlements")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspaces.getEntitlements();
        expect(response).toEqual(rawResponseBody);
    });

    test("getEntitlements (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/workspaces/current/entitlements")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workspaces.getEntitlements();
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("getEntitlements (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/workspaces/current/entitlements")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workspaces.getEntitlements();
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("getEntitlements (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/workspaces/current/entitlements")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workspaces.getEntitlements();
        }).rejects.toThrow(Speechify.InternalServerError);
    });
});
