// This file was auto-generated by Fern from our API Definition.

export interface SpeechifyEnvironmentUrls {
    base: string;
    production: string;
}

export const SpeechifyEnvironment = {
    Default: {
        base: "https://api.speechify.ai",
        production: "wss://api.speechify.ai",
    },
} as const;

export type SpeechifyEnvironment = typeof SpeechifyEnvironment.Default;
