// This file was auto-generated by Fern from our API Definition.

import * as Speechify from "../../../src/api/index";
import { SpeechifyClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("KeysClient", () => {
    test("listKeys (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            next_cursor: "next_cursor",
            has_more: true,
            keys: [
                {
                    id: "ckey_01jqr8x9zg5k2m3n4p5q6r7s8t",
                    api_id: "api_id",
                    name: "name",
                    key_hint: "ck_ab12••••wxyz",
                    rate_per_minute: 1,
                    secret: "secret",
                    revoked_at: "2024-01-15T09:30:00Z",
                    last_used_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/keys")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.hostedApis.keys.listKeys({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });

        expect(expected.keys).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.keys).toEqual(nextPage.data);
    });

    test("listKeys (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("listKeys (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("listKeys (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("listKeys (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("listKeys (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("listKeys (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/apis/api_id/keys")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.listKeys({
                api_id: "api_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("createKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "ckey_01jqr8x9zg5k2m3n4p5q6r7s8t",
            api_id: "api_id",
            name: "name",
            key_hint: "ck_ab12••••wxyz",
            rate_per_minute: 1,
            secret: "secret",
            revoked_at: "2024-01-15T09:30:00Z",
            last_used_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/keys")
            .header("Idempotency-Key", "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.keys.createKey({
            "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("createKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("createKey (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("createKey (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("createKey (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.ConflictError);
    });

    test("createKey (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("createKey (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.createKey({
                api_id: "api_id",
                name: "name",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });

    test("revokeKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "ckey_01jqr8x9zg5k2m3n4p5q6r7s8t",
            api_id: "api_id",
            name: "name",
            key_hint: "ck_ab12••••wxyz",
            rate_per_minute: 1,
            secret: "secret",
            revoked_at: "2024-01-15T09:30:00Z",
            last_used_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/apis/api_01jqr8x9zg5k2m3n4p5q6r7s8t/keys/ckey_01jqr8x9zg5k2m3n4p5q6r7s8t/revoke")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hostedApis.keys.revokeKey({
            api_id: "api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            consumer_key_id: "ckey_01jqr8x9zg5k2m3n4p5q6r7s8t",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.BadRequestError);
    });

    test("revokeKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.UnauthorizedError);
    });

    test("revokeKey (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.PaymentRequiredError);
    });

    test("revokeKey (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.NotFoundError);
    });

    test("revokeKey (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.TooManyRequestsError);
    });

    test("revokeKey (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SpeechifyClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { code: "bad_request", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/apis/api_id/keys/consumer_key_id/revoke")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.hostedApis.keys.revokeKey({
                api_id: "api_id",
                consumer_key_id: "consumer_key_id",
            });
        }).rejects.toThrow(Speechify.InternalServerError);
    });
});
