// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
 *         full_name: "Jane Doe"
 *     }
 */
export interface CreateConsentChallengeRequest {
    /**
     * A client-generated key (an opaque string, max 255 chars) that makes a
     * side-effect POST safe to retry: the server runs the operation exactly
     * once and replays the first response (its status and body) for 24 hours.
     * Reusing a key with a different request body, or while the first request
     * is still in flight, returns `409 idempotency_conflict`. A replayed
     * response carries the `Idempotent-Replayed: true` header.
     */
    "Idempotency-Key"?: string;
    /**
     * Full name of the person consenting to have their voice cloned.
     * Speechify binds it to the challenge and stores it with the consent
     * record, so the create that consumes the challenge does not carry it
     * and cannot change it.
     *
     * At most 120 bytes once UTF-8 encoded, which is 120 characters of
     * Latin script but around 40 of Chinese, Japanese or Korean. Stated in
     * bytes rather than as a `maxLength` because the two only agree on
     * single-byte scripts, and a character count that never over-accepts
     * would have to refuse Latin names at 30. A name over the limit comes
     * back as `validation_failed` reporting its measured length.
     */
    full_name: string;
}
